language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run docs:build
before_install:
- openssl aes-256-cbc -K $encrypted_c0bd9ff5c410_key -iv $encrypted_c0bd9ff5c410_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- scp -r docs/.vuepress/dist/ travis@47.96.14.140:/home/travis/website/vuepress-docs
- ssh travis@47.96.14.140 -o StrictHostKeyChecking=no "nginx -s reload"
addons:
  ssh_known_hosts: 47.96.14.140